######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 18 20:27:35 2013
######################################################################

TEMPLATE = app
TARGET = Tormoz1
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
RESOURCES += images.qrc
