######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 27 16:46:20 2013
######################################################################

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = Tormoz1
DEPENDPATH += . release
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
RESOURCES += images.qrc
